### ISSUE TITLE
color becomes white when updating length

### ISSUE THREAD

**Issue by Jozys** [ProjektDevLights/Hardware#46]

**Comment by TPausL** [comment]
was genau meinst du bei mit ändert sich nichts wenn ich die länge änderre?

**Comment by Jozys** [comment]
Wenn ich die Länge update dann wird die Farbe weiß, nicht die Farbe die ich vorher drin hatte. Vielleicht liegt das auch am Strom idk

**Comment by TPausL** [comment]
kannst du mir die farbe vorher und die länge vorher und nacher mal sagen, dann kann ich nochmal gucken und welches muster

**Comment by Jozys** [comment]
Habe das mit mehreren Farben probiert.

Unter anderem mit diesem Gradient ["#0000FF", "#00FFFF"] und ["FF1F1F", "#D7FF00"] und den einzelnen Farben aus diesen Gradients und die Länge auch mit random von mir ausgewählten Zahlen

**Comment by TPausL** [comment]
sieht bei mir ganz gut aus

manchmal sind die gradient nicht ganz clean, hören also bisschen eher auf wegen der interpolation

**Comment by Jozys** [comment]
Das Problem ist aber, dass die Farbe beim ÄNDERN der Länge komplett weiß wird. Nicht nur ein bisschen falsch sondern komplett weiß

**Comment by TPausL** [comment]
hmmm

"can't reproduce"

**Comment by Jozys** [comment]
Ahhhh dann kickt der Strom wahrscheinlich wieder 

--> Weirde Bugs auf den Strom schieben

**Comment by TPausL** [comment]
ja
