### ISSUE TITLE
ESP CRASHES FOR LENGTH ONE

### ISSUE THREAD

**Issue by TPausL** [ProjektDevLights/Hardware#49]

**Comment by TPausL** [comment]
wahrscheinlich interpolation

**Comment by TPausL** [comment]
ne immer

**Comment by Jozys** [comment]
Es lag an der Interpolation, die aber beim Updaten der Länge ausgeführt wurde und bei einer Länge von 1 zum Absturz des ESPs führte.

**Comment by TPausL** [comment]
Aber du hast doch nichts an der Interpolation gemacht??

**Comment by Jozys** [comment]
Huch hab was falsch verstanden. Das eigentliche Problem bestand bei der Methode getFirstRunLed die bei der passenden Berechnung bei einer Länge von 1 zum Absturz führte.
Sorrry. 😅
